services:
  database:
    image: nevatech/sentinet.database.linux:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: mJ41C-36gQ[P
    ports:
      - "6123:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "mJ41C-36gQ[P" -C -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  repository:
    image: nevatech/sentinet.linux:latest
    command: Nevatech.Sentinet.Repository.dll
    environment:
      SENTINET_CONFIG: /config/repository.json
    ports:
      - "7000:80"
      - "7001:443"
    configs:
      - source: repository
        target: /config/repository.json
      - source: certificate
        target: /config/host.docker.internal.pfx
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  agent:
    image: nevatech/sentinet.linux:latest
    command: Nevatech.Sentinet.Agent.dll
    environment:
      SENTINET_CONFIG: /config/agent.json
    configs:
      - source: agent
        target: /config/agent.json
      - source: certificate
        target: /config/host.docker.internal.pfx
    depends_on:
      database:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node:
    image: nevatech/sentinet.linux:latest
    command: Nevatech.Sentinet.Node.dll
    environment:
      SENTINET_CONFIG: /config/node.json
    ports:
      - "5000:80"
      - "5001:443"
    configs:
      - source: node
        target: /config/node.json
      - source: certificate
        target: /config/host.docker.internal.pfx
    depends_on:
      - repository
    extra_hosts:
      - "host.docker.internal:host-gateway"

configs:
  repository:
    file: config/repository.json
  certificate:
    file: config/host.docker.internal.pfx
  agent:
    file: config/agent.json
  node:
    file: config/node.json
