apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: sentinet
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 1433
    name: sql
  selector:
    app: database
---
apiVersion: v1
kind: Service
metadata:
  name: repository-svc
  namespace: sentinet
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7001
    targetPort: 443
    name: https
  - protocol: TCP
    port: 7000
    targetPort: 80
    name: http
  selector:
    app: repository
---
apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: sentinet
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 443
    name: https
  - protocol: TCP
    port: 5000
    targetPort: 80
    name: http
  selector:
    app: node
